### ISSUE TITLE
Change ROS exports

### ISSUE THREAD

**Issue by lmark1** [larics/uav_nuc_setup#1]
Change ROS exports to suit the remote master workflow as follows:

```bash
MY_HOSTNAME=$(cat /etc/hostname)

# ROS namespace used in all nodes.
export UAV_NAMESPACE=$MY_HOSTNAME
export ROS_MASTER_URI=http://$MY_HOSTNAME.local:11311
export ROS_IP=$MY_HOSTNAME.local
export ROS_HOSTNAME=$MY_HOSTNAME.local
```

**Comment by mkrizmancic** [comment]
What's wrong with the current setup using the USER environment variable?

**Comment by lmark1** [comment]
Hawk1 setup was:
```bash
export ROS_MASTER_URI=http://192.168.1.61:11311
export ROS_IP=192.168.1.61
# Without hostname
```
[This](https://github.com/larics/uav_nuc_setup/blob/5c26e022af2cabaac95f92cb03514d68ec36378d/scripts/setup.sh#L114) works fine. My bad!
